### ISSUE TITLE
[Not an issue][Another app idea to address] An app like "Bla bla Car" but for goods being frightened in urban environments

### ISSUE THREAD

**Issue by mustafa-yilmaz-zz** [Meteor-Mentor/meteor_mentor#18]
To become a learning path for some of us, I would like to share (and offer) here an app idea to address in this community. It would also probably take quite more time for me to develop it by only my personal efforts since I am a real JavaScript newbie (developed nothing with it so far) let alone the Meteor platform itself. Therefore, I guess, sharing it here is probably the best option to speed the process of the idea-to-development stage up.

So here is the idea ;

An app that will help people to add their needs into the deliveries being already planned to arrive their neighborhood (as also explained on LinkedIn at  http://www.linkedin.com/pulse/delivery-close-you-would-like-add-your-orders-mustafa-yilmaz ). In short, an app does for goods being distributed in urban areas what "Bla Bla Car" does for travellers; "sharing of deliveries".   

I would like to learn JS and Meteor both by building the idea above. 

Where should we start from?
What do you (people in this community) suggest me (us)?
Anyone here can guide me (us)?
Might it be possible for us to be a kind of a remote-team?

Thanks in advance for any contribution. 

Looking forward to hear from someone soon. I am lost in tutorials, books and videos etc. ( the problem which triggered @ChristBKK to light the spark of this community at http://forums.meteor.com/t/mastermind-group-1/16476 ) .

**Comment by serkandurusoy** [comment]
Hi @mustafa-yilmaz and thank you for seeking our advice. But the problem is, this repository is created for a specific application and your question is not related to it.

The best place to ask such questions is the meteor forums and I'm sure the community will do its best to help out. Also you happen to be one of the first people to get involved with the meteor-mentor group but unfortunately we had not heard from you ever since. We even tried to ping you directly, and unfortunately, we had to assume you were not interested.

Anyway, let us (not here, on the forums please) know if you want to get back into the group, but you should definitely first repost your questions on its own thread on the forums so that a much broader community can get involved.

Thanks.
